apiVersion: v1
kind: Service
metadata:
  app: {{ template "flask-app.fullname" . }}
  chart: {{ template "flask-app.chart" . }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ template "flask-app.fullname" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}